workflows:
  my-workflow:
    environment:
      flutter: stable
  build:
    scripts:
      - name: Build Android App Bundle
        working_directory: example
        script: flutter build apk
    artifacts:
      - android/build/**/outputs/bundle/**/*.apk


